.\" 
.\" gnome-session-save manual page.
.\" (C) 2000 Miguel de Icaza (miguel@helixcode.com)
.\"
.TH GNOME-SESSION-SAVE 1 "GNOME"
.SH NAME
gnome-session-save \- Ends the current GNOME session
.SH SYNOPSIS
.B gnome-session-save [\-\-logout] [\-\-force\-logout] [\-\-logout\-dialog] [\-\-shutdown\-dialog] [\-\-gui] [\-\-kill [\-\-silent]]
.SH DESCRIPTION
\fIgnome-session-save\fP can be used to log out of a GNOME session.  It's
called \fIgnome-session-save\fP instead of gnome-session-logout for historical
reasons.
.PP
The \fB\-\-gui\fP option will report errors in dialog boxes instead of
printing to stderr.

If called with the \fB\-\-logout\fP option, the current GNOME session will be
ended, unless logging out has been inhibited by an application.  The
\fB\-\-force\-logout\fP option can be used to end the session regardless of
the inhibition state.

When the \fB\-\-logout\-dialog\fP option is given, the standard dialog
displaying logout options is displayed.  When \fB\-\-shutdown\-dialog\fP
option is given, the standard dialog displaying shutdown options is
displayed.

The \fB\-\-kill\fP and \fB\-\-silent\fP options are deprecated.  The
\fB\-\-kill\fP option is equivalent to the \fB\-\-logout\-dialog\fP
option.  If \fB\-\-silent\fP is used with \fB\-\-kill\fR, then it will
behave as if \fB\-\-logout\fP was used.

.SH SEE ALSO
.BR gnome-session(1)
.SH BUGS
If you find bugs in the \fIgnome-session-save\fP program, please report
these on http://bugzilla.gnome.org.
